jobPortal/core/urls.py
from django.urls import path
from .views import *
app_name = 'core'  

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
]

jobPortal/jobPortal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('core.urls','core'),namespace='core')),
    path('accounts/',include(('accounts.urls','accounts'),namespace='accounts')),
    path('users/', include('users.urls', namespace='users')),
    path('employers/', include('employers.urls', namespace='employers')),
    path('administrator/', include('admin_dashboard.urls', namespace='admin_dashboard')),  
     
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobPortal/users/urls.py
from django.urls import path
from .views import *

app_name = 'users' 

urlpatterns = [
    path('complete-profile/', UserProfileForm.as_view(), name='complete-profile'),
    path('jobs/', UserHome.as_view(), name='jobs'),
    path('job-details/', JobDetails.as_view(), name='job-details'),

    
]

jobPortal/accounts/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class CustomUser(AbstractUser):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    COUNTRY_CHOICES = (
        ('IN', 'India'),
    )

    email = models.EmailField(
        'email address', unique=True, blank=False, null=False)
    phone = models.CharField(max_length=15, blank=True, null=True)
    profile_photo = models.ImageField(
        upload_to='user_photos/', blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    short_bio = models.TextField(max_length=500, blank=True, null=True)
    job_title = models.CharField(max_length=255, blank=True, null=True)
    gender = models.CharField(
        max_length=1, default='M', choices=GENDER_CHOICES)
    country = models.CharField(
        max_length=50, default='IN', choices=COUNTRY_CHOICES)
    open_to_hiring = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def age(self):
        if self.dob:
            today = date.today()
            return today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))
        return None


class Address(models.Model):
    COUNTRY_CHOICES = (
        ('IN', 'India'),
    )
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=15)
    address_line_1 = models.TextField(max_length=250)
    address_line_2 = models.TextField(max_length=250)
    address_line_3 = models.TextField(max_length=250)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    country = models.CharField(
        max_length=50, default='IN', choices=COUNTRY_CHOICES)
    pincode = models.CharField(max_length=25)
    phone = models.CharField(max_length=15, blank=True, null=True)
    is_default = models.BooleanField(default=True)

    class Meta:
        unique_together = ['user', 'name']

    def __str__(self):
        return f'''{self.address_line_1}
        {self.address_line_2}
        {self.address_line_3}'''


class Hobby(models.Model):
    HOBBY_CHOICES = (
        ('Reading', 'Reading'),
        ('Traveling', 'Traveling'),
        ('Cooking', 'Cooking'),
        ('Sports', 'Sports'),
        ('Gardening', 'Gardening'),
        ('Gaming', 'Gaming'),
        ('Fitness', 'Fitness'),
        ('Photography', 'Photography'),
        ('Writing', 'Writing'),
        ('Dancing', 'Dancing'),
    )

    name = models.CharField(max_length=100, choices=HOBBY_CHOICES, unique=True)

    def __str__(self):
        return self.name
    
class Interest(models.Model):
    INTEREST_CHOICES = (
        ('Technology', 'Technology'),
        ('Science', 'Science'),
        ('Literature', 'Literature'),
        ('Travel', 'Travel'),
        ('Food', 'Food'),
        ('Health', 'Health'),
        ('Fitness', 'Fitness'),
        ('Education', 'Education'),
        ('Fashion', 'Fashion'),
        ('Entertainment', 'Entertainment'),
        ('Finance', 'Finance'),
        ('Politics', 'Politics'),
        ('Environment', 'Environment'),
        ('Sports', 'Sports'),
        ('History', 'History'),
    )
    
    name = models.CharField(max_length=100, choices=INTEREST_CHOICES, unique=True)

    def __str__(self):
        return self.name

class UserActivity(models.Model):
    user = models.ForeignKey(CustomUser, related_name='user_activities', on_delete=models.CASCADE)
    hobbies = models.ManyToManyField(Hobby, related_name='user_activities')
    Interest = models.ManyToManyField(Interest, related_name='user_activities')
    smoking_habit = models.BooleanField(default=False)
    drinking_habit = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username


class UserQualifications(models.Model):
    LEVEL_CHOICES = (
        ('High School', 'High School'),
        ('Diploma', 'Diploma'),
        ('Undergraduate', 'Undergraduate'),
        ('Graduate', 'Graduate'),
        ('Postgraduate', 'Postgraduate'),
        ('PhD', 'PhD'),
        ('Other', 'Other'),
    )

    user = models.ForeignKey(CustomUser, related_name='user_qualifications', on_delete=models.CASCADE)
    level = models.CharField(max_length=20, choices=LEVEL_CHOICES)
    start_date = models.DateField()
    end_date = models.DateField()
    course = models.CharField(max_length=100)
    institution = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.level} at {self.institution}"

jobPortal/users/models.py
from django.db import models

from accounts.models import CustomUser

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='profile')
    work_status = models.CharField(max_length=50, choices=[('F', 'Fresher'), ('E', 'Experienced')])
    phone_number = models.CharField(max_length=15, blank=True)
    contact_email = models.EmailField()
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    resume = models.FileField(upload_to='resumes/', blank=True, null=True)
    languages = models.TextField(blank=True)
    location = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.username

class Skill(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='skills')
    skill_name = models.CharField(max_length=100)
    years_of_exp = models.CharField(max_length=2)

class Certification(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='certifications')
    certification_name = models.TextField()
    expiration_date = models.DateField()

class Education(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='educations')
    level_of_education = models.CharField(max_length=100, choices=[
        ('Bachelors', 'Bachelors'),
        ('Masters', 'Masters'),
        ('PhD', 'PhD'),
        ('Diploma', 'Diploma'),
        ('Certification', 'Certification')
    ])
    course_name = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.level_of_education} in {self.course_name}"

class Experience(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='experiences')
    job_title = models.CharField(max_length=100)
    company_name = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.job_title} at {self.company_name}"

jobPortal/users/forms.py
from django import forms

from .models import *


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['work_status', 'phone_number', 'contact_email', 'profile_picture', 'resume', 'languages', 'location']

class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ['skill_name', 'years_of_exp']

class CertificationForm(forms.ModelForm):
    class Meta:
        model = Certification
        fields = ['certification_name', 'expiration_date']

class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ['level_of_education', 'course_name']

class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = ['job_title', 'company_name']

jobPortal/users/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class UserProfileForm(LoginRequiredMixin,TemplateView):
    template_name = 'users/complete_profile.html'
    
class UserHome(LoginRequiredMixin,TemplateView):
    template_name = 'users/user_home.html'
    
class JobDetails(TemplateView):
    template_name = 'users/job_detail.html'

jobPortal/templates/users/Add_address.html
         <!-- Address -->
          
         <div class="card mb-4">
            <div class="card-body">
              <h3 class="h6 mb-4">Address</h3>
              <div class="mb-3">
                <label class="form-label">Address Line 1</label>
                <input type="text" class="form-control">
              </div>
              <div class="mb-3">
                <label class="form-label">Address Line 2</label>
                <input type="text" class="form-control">
              </div>
              <div class="row">
                <div class="col-lg-6">
                  <div class="mb-3">
                    <label class="form-label">Country</label>
                    <select class="select2 form-control select2-hidden-accessible" data-select2-placeholder="Select country" data-select2-id="select2-data-1-gy14" tabindex="-1" aria-hidden="true">
                      <option data-select2-id="select2-data-3-ibs9"></option>
                      <option value="AF">Afghanistan</option>
                      <option value="BS">Bahamas</option>
                      <option value="KH">Cambodia</option>
                      <option value="DK">Denmark</option>
                      <option value="TL">East Timor</option>
                      <option value="GM">Gambia</option>
                    </select><span class="select2 select2-container select2-container--bootstrap-5" dir="ltr" data-select2-id="select2-data-2-46y9" style="width: 391px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-vp8l-container" aria-controls="select2-vp8l-container"><span class="select2-selection__rendered" id="select2-vp8l-container" role="textbox" aria-readonly="true" title="Select country"><span class="select2-selection__placeholder">Select country</span></span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="mb-3">
                    <label class="form-label">State</label>
                    <select class="select2 form-control select2-hidden-accessible" data-select2-placeholder="Select state" data-select2-id="select2-data-4-680y" tabindex="-1" aria-hidden="true">
                      <option data-select2-id="select2-data-6-cshs"></option>
                      <option value="AL">Alabama</option>
                      <option value="CA">California</option>
                      <option value="DE">Delaware</option>
                      <option value="FL">Florida</option>
                      <option value="GA">Georgia</option>
                      <option value="HI">Hawaii</option>
                      <option value="ID">Idaho</option>
                      <option value="KS">Kansas</option>
                    </select><span class="select2 select2-container select2-container--bootstrap-5" dir="ltr" data-select2-id="select2-data-5-np4c" style="width: 391px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-2fn7-container" aria-controls="select2-2fn7-container"><span class="select2-selection__rendered" id="select2-2fn7-container" role="textbox" aria-readonly="true" title="Select state"><span class="select2-selection__placeholder">Select state</span></span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-6">
                  <div class="mb-3">
                    <label class="form-label">City</label>
                    <select class="select2 form-control select2-hidden-accessible" data-select2-placeholder="Select city" data-select2-id="select2-data-7-809c" tabindex="-1" aria-hidden="true">
                      <option data-select2-id="select2-data-9-k35n"></option>
                      <option value="b">Bangkok</option>
                      <option value="d">Dubai</option>
                      <option value="h">Hong Kong</option>
                      <option value="k">Kuala Lumpur</option>
                      <option value="l">London</option>
                      <option value="n">New York City</option>
                      <option value="m">Macau</option>
                      <option value="p">Paris</option>
                    </select><span class="select2 select2-container select2-container--bootstrap-5" dir="ltr" data-select2-id="select2-data-8-3peu" style="width: 391px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-jdfi-container" aria-controls="select2-jdfi-container"><span class="select2-selection__rendered" id="select2-jdfi-container" role="textbox" aria-readonly="true" title="Select city"><span class="select2-selection__placeholder">Select city</span></span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="mb-3">
                    <label class="form-label">ZIP code</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Right side -->
        <div class="col-lg-4">
          <!-- Status -->
          <div class="card mb-4">
            <div class="card-body">
              <h3 class="h6">Status</h3>
              <select class="form-select">
                <option value="draft" selected="">Draft</option>
                <option value="active">Active</option>
                <option value="active">Inactive</option>
              </select>
            </div>
          </div>
          <!-- Avatar -->
          <div class="card mb-4">
            <div class="card-body">
              <h3 class="h6">Avatar</h3>
              <input class="form-control" type="file">
            </div>
          </div>
          <!-- Notes -->
          <div class="card mb-4">
            <div class="card-body">
              <h3 class="h6">Notes</h3>
              <textarea class="form-control" rows="3"></textarea>
            </div>
          </div>

jobPortal/templates/users/complete_profile.html
{% extends "base.html" %}

{% block title %}Complete Profile{% endblock %}


{% block content %}
<div class="container-fluid mt-5">

  <div class="container">
    <!-- Title -->
    <div class="d-flex justify-content align-items-lg-center py-3 flex-column flex-lg-row">
      <h2 class="h5 mb-3 mb-lg-0 text-primary"><a href="../../pages/admin/customers.html" class="text-muted"><i
            class="bi bi-arrow-left-square me-2 "></i></a> Setup Profile</h2>
    </div>
    <!-- Main content -->
    <div class="row">
      <!-- Left side -->

      <div class="col-lg-12">
        <!-- Basic information -->
        <div class="card mb-4">
          <div class="card-body">
            <h3 class="h6 mb-4">Basic information</h3>
            <div class="row">
              <div class="col-lg-6">
                <div class="mb-3">
                  <label class="form-label">First name</label>
                  <input type="text" class="form-control">
                </div>
              </div>
              <div class="col-lg-6">
                <div class="mb-3">
                  <label class="form-label">Last name</label>
                  <input type="text" class="form-control">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-4">
                <div class="mb-3">
                  <label class="form-label">Phone number</label>
                  <input type="text" class="form-control">
                </div>
              </div>
              <div class="col-lg-3">
                <div class="mb-3">
                  <label class="form-label">Gender</label>
                  <select class="form-select">
                    <option value="draft" selected="">Draft</option>
                    <option value="active">Active</option>
                    <option value="active">Inactive</option>
                  </select>
                </div>
              </div>

              <div class="col-lg-3">
                <div class="mb-3">
                  <label class="form-label">Country</label>
                  <select class="form-select">
                    <option value="draft" selected="">Draft</option>
                    <option value="active">Active</option>
                    <option value="active">Inactive</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6">

                <label class="form-label">Profile Picture</label>

                <input class="form-control" type="file">
              </div>

            </div>

            <div class="row ">
              <div class="col"></div>
              <div class="col-auto">

                <button type="submit" class="btn btn-primary pl-4 pr-4">Next</button>
              </div>

            </div>


          </div>
        </div>


      </div>
    </div>
  </div>

</div>
{% block extra_script %}

{% endblock %}

{% endblock %}

jobPortal/templates/users/job-detail.html
{% extends "base.html" %}

{% block title %}User Home{% endblock %}




{% block content %}
        <!-- Job Detail Start -->
            
        
        <div class="container-xxl rounded shadow py-5 wow fadeInUp bg-white border" data-wow-delay="0.1s">
            <div class="container">
                <div class="row gy-5 gx-4">
                    <div class="col-lg-8">
                        <div class="d-flex align-items-center mb-5">
                            <img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-2.jpg" alt="" style="width: 80px; height: 80px;">
                            <div class="text-start ps-4">
                                <h3 class="mb-3">Marketing Manager</h3>
                                <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>
                                <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>
                                <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>
                            </div>
                        </div>

                        <div class="mb-5">
                            <h4 class="mb-3">Job description</h4>
                            <p>Dolor justo tempor duo ipsum accusam rebum gubergren erat. Elitr stet dolor vero clita labore gubergren. Kasd sed ipsum elitr clita rebum ut sea diam tempor. Sadipscing nonumy vero labore invidunt dolor sed, eirmod dolore amet aliquyam consetetur lorem, amet elitr clita et sed consetetur dolore accusam. Vero kasd nonumy justo rebum stet. Ipsum amet sed lorem sea magna. Rebum vero dolores dolores elitr vero dolores magna, stet sea sadipscing stet et. Est voluptua et sanctus at sanctus erat vero sed sed, amet duo no diam clita rebum duo, accusam tempor takimata clita stet nonumy rebum est invidunt stet, dolor.</p>
                            <h4 class="mb-3">Responsibility</h4>
                            <p>Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor</p>
                            <ul class="list-unstyled">
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Dolor justo tempor duo ipsum accusam</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Elitr stet dolor vero clita labore gubergren</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Rebum vero dolores dolores elitr</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Est voluptua et sanctus at sanctus erat</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Diam diam stet erat no est est</li>
                            </ul>
                            <h4 class="mb-3">Qualifications</h4>
                            <p>Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor</p>
                            <ul class="list-unstyled">
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Dolor justo tempor duo ipsum accusam</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Elitr stet dolor vero clita labore gubergren</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Rebum vero dolores dolores elitr</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Est voluptua et sanctus at sanctus erat</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Diam diam stet erat no est est</li>
                            </ul>



                            <h4 class="mb-4">Job Summery</h4>
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Published On: 01 Jan, 2045</p>
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Vacancy: 123 Position</p>
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Job Nature: Full Time</p>
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Salary: $123 - $456</p>
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Location: New York, USA</p>
                            <p class="m-0"><i class="fa fa-angle-right text-primary me-2"></i>Date Line: 01 Jan, 2045</p>
                        </div>
        
               
                    </div>
        
             
                </div>
            </div>
        </div>
        <!-- Job Detail End -->
 

        {% endblock %}

jobPortal/templates/users/user_activities.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
    crossorigin="anonymous"
  />
  <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>
<body class="container mt-5">
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>
</body>
<script>
    $("#id_hobbies").select2();
    $("#id_Interest").select2();

</script>
</html>

jobPortal/templates/users/user_details.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
    crossorigin="anonymous"
  />
  <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>
<body class="container mt-5">
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>
</body>
<script>
    $("#id_hobbies").select2();
</script>
</html>

jobPortal/templates/users/user_qualifications.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
    crossorigin="anonymous"
  />

  <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.3/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.3/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
  <script src="https://code.jquery.com/ui/1.13.3/jquery-ui.js"></script>
</head>
<body class="container mt-5">
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>
</body>
<script>
    $("#id_level").select2();
    $("#id_Interest").select2();

</script>
<script>
    $( function() {
      $( "#id_start_date" ).datepicker();
      $( "#id_end_date" ).datepicker();
    } );
    </script>
</html>